/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSendRouteImport } from './routes/_authenticated.send'
import { Route as AuthenticatedOutboxRouteImport } from './routes/_authenticated.outbox'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated.onboarding'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated.home'
import { Route as AuthenticatedMeIndexRouteImport } from './routes/_authenticated.me.index'
import { Route as AuthenticatedThreadThreadIdRouteImport } from './routes/_authenticated.thread.$threadId'
import { Route as AuthenticatedMeEditRouteImport } from './routes/_authenticated.me.edit'
import { Route as AuthenticatedMeBlockedRouteImport } from './routes/_authenticated.me.blocked'
import { Route as AuthenticatedDeliveryDeliveryIdRouteImport } from './routes/_authenticated.delivery.$deliveryId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSendRoute = AuthenticatedSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOutboxRoute = AuthenticatedOutboxRouteImport.update({
  id: '/outbox',
  path: '/outbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeIndexRoute = AuthenticatedMeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedThreadThreadIdRoute =
  AuthenticatedThreadThreadIdRouteImport.update({
    id: '/thread/$threadId',
    path: '/thread/$threadId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeEditRoute = AuthenticatedMeEditRouteImport.update({
  id: '/me/edit',
  path: '/me/edit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeBlockedRoute = AuthenticatedMeBlockedRouteImport.update({
  id: '/me/blocked',
  path: '/me/blocked',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDeliveryDeliveryIdRoute =
  AuthenticatedDeliveryDeliveryIdRouteImport.update({
    id: '/delivery/$deliveryId',
    path: '/delivery/$deliveryId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/outbox': typeof AuthenticatedOutboxRoute
  '/send': typeof AuthenticatedSendRoute
  '/delivery/$deliveryId': typeof AuthenticatedDeliveryDeliveryIdRoute
  '/me/blocked': typeof AuthenticatedMeBlockedRoute
  '/me/edit': typeof AuthenticatedMeEditRoute
  '/thread/$threadId': typeof AuthenticatedThreadThreadIdRoute
  '/me/': typeof AuthenticatedMeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/outbox': typeof AuthenticatedOutboxRoute
  '/send': typeof AuthenticatedSendRoute
  '/delivery/$deliveryId': typeof AuthenticatedDeliveryDeliveryIdRoute
  '/me/blocked': typeof AuthenticatedMeBlockedRoute
  '/me/edit': typeof AuthenticatedMeEditRoute
  '/thread/$threadId': typeof AuthenticatedThreadThreadIdRoute
  '/me': typeof AuthenticatedMeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/outbox': typeof AuthenticatedOutboxRoute
  '/_authenticated/send': typeof AuthenticatedSendRoute
  '/_authenticated/delivery/$deliveryId': typeof AuthenticatedDeliveryDeliveryIdRoute
  '/_authenticated/me/blocked': typeof AuthenticatedMeBlockedRoute
  '/_authenticated/me/edit': typeof AuthenticatedMeEditRoute
  '/_authenticated/thread/$threadId': typeof AuthenticatedThreadThreadIdRoute
  '/_authenticated/me/': typeof AuthenticatedMeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/home'
    | '/onboarding'
    | '/outbox'
    | '/send'
    | '/delivery/$deliveryId'
    | '/me/blocked'
    | '/me/edit'
    | '/thread/$threadId'
    | '/me/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/home'
    | '/onboarding'
    | '/outbox'
    | '/send'
    | '/delivery/$deliveryId'
    | '/me/blocked'
    | '/me/edit'
    | '/thread/$threadId'
    | '/me'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/home'
    | '/_authenticated/onboarding'
    | '/_authenticated/outbox'
    | '/_authenticated/send'
    | '/_authenticated/delivery/$deliveryId'
    | '/_authenticated/me/blocked'
    | '/_authenticated/me/edit'
    | '/_authenticated/thread/$threadId'
    | '/_authenticated/me/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/send': {
      id: '/_authenticated/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof AuthenticatedSendRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/outbox': {
      id: '/_authenticated/outbox'
      path: '/outbox'
      fullPath: '/outbox'
      preLoaderRoute: typeof AuthenticatedOutboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/': {
      id: '/_authenticated/me/'
      path: '/me'
      fullPath: '/me/'
      preLoaderRoute: typeof AuthenticatedMeIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/thread/$threadId': {
      id: '/_authenticated/thread/$threadId'
      path: '/thread/$threadId'
      fullPath: '/thread/$threadId'
      preLoaderRoute: typeof AuthenticatedThreadThreadIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/edit': {
      id: '/_authenticated/me/edit'
      path: '/me/edit'
      fullPath: '/me/edit'
      preLoaderRoute: typeof AuthenticatedMeEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/blocked': {
      id: '/_authenticated/me/blocked'
      path: '/me/blocked'
      fullPath: '/me/blocked'
      preLoaderRoute: typeof AuthenticatedMeBlockedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/delivery/$deliveryId': {
      id: '/_authenticated/delivery/$deliveryId'
      path: '/delivery/$deliveryId'
      fullPath: '/delivery/$deliveryId'
      preLoaderRoute: typeof AuthenticatedDeliveryDeliveryIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOutboxRoute: typeof AuthenticatedOutboxRoute
  AuthenticatedSendRoute: typeof AuthenticatedSendRoute
  AuthenticatedDeliveryDeliveryIdRoute: typeof AuthenticatedDeliveryDeliveryIdRoute
  AuthenticatedMeBlockedRoute: typeof AuthenticatedMeBlockedRoute
  AuthenticatedMeEditRoute: typeof AuthenticatedMeEditRoute
  AuthenticatedThreadThreadIdRoute: typeof AuthenticatedThreadThreadIdRoute
  AuthenticatedMeIndexRoute: typeof AuthenticatedMeIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOutboxRoute: AuthenticatedOutboxRoute,
  AuthenticatedSendRoute: AuthenticatedSendRoute,
  AuthenticatedDeliveryDeliveryIdRoute: AuthenticatedDeliveryDeliveryIdRoute,
  AuthenticatedMeBlockedRoute: AuthenticatedMeBlockedRoute,
  AuthenticatedMeEditRoute: AuthenticatedMeEditRoute,
  AuthenticatedThreadThreadIdRoute: AuthenticatedThreadThreadIdRoute,
  AuthenticatedMeIndexRoute: AuthenticatedMeIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
