/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated.notifications'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated.me'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated.home'
import { Route as AuthenticatedGridRouteImport } from './routes/_authenticated.grid'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated.feed'
import { Route as AuthenticatedBacklogRouteImport } from './routes/_authenticated.backlog'
import { Route as AuthenticatedUHandleRouteImport } from './routes/_authenticated.u.$handle'
import { Route as AuthenticatedQuestionQuestionIdRouteImport } from './routes/_authenticated.question.$questionId'
import { Route as AuthenticatedMeEditRouteImport } from './routes/_authenticated.me.edit'
import { Route as AuthenticatedMeBlockedRouteImport } from './routes/_authenticated.me.blocked'
import { Route as AuthenticatedAnswerQuestionIdRouteImport } from './routes/_authenticated.answer.$questionId'
import { Route as AuthenticatedAnswerDetailAnswerIdRouteImport } from './routes/_authenticated.answer-detail.$answerId'
import { Route as AuthenticatedUHandleFollowingRouteImport } from './routes/_authenticated.u.$handle.following'
import { Route as AuthenticatedUHandleFollowersRouteImport } from './routes/_authenticated.u.$handle.followers'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGridRoute = AuthenticatedGridRouteImport.update({
  id: '/grid',
  path: '/grid',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBacklogRoute = AuthenticatedBacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUHandleRoute = AuthenticatedUHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuestionQuestionIdRoute =
  AuthenticatedQuestionQuestionIdRouteImport.update({
    id: '/question/$questionId',
    path: '/question/$questionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeEditRoute = AuthenticatedMeEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AuthenticatedMeRoute,
} as any)
const AuthenticatedMeBlockedRoute = AuthenticatedMeBlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => AuthenticatedMeRoute,
} as any)
const AuthenticatedAnswerQuestionIdRoute =
  AuthenticatedAnswerQuestionIdRouteImport.update({
    id: '/answer/$questionId',
    path: '/answer/$questionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnswerDetailAnswerIdRoute =
  AuthenticatedAnswerDetailAnswerIdRouteImport.update({
    id: '/answer-detail/$answerId',
    path: '/answer-detail/$answerId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUHandleFollowingRoute =
  AuthenticatedUHandleFollowingRouteImport.update({
    id: '/following',
    path: '/following',
    getParentRoute: () => AuthenticatedUHandleRoute,
  } as any)
const AuthenticatedUHandleFollowersRoute =
  AuthenticatedUHandleFollowersRouteImport.update({
    id: '/followers',
    path: '/followers',
    getParentRoute: () => AuthenticatedUHandleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/backlog': typeof AuthenticatedBacklogRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/grid': typeof AuthenticatedGridRoute
  '/home': typeof AuthenticatedHomeRoute
  '/me': typeof AuthenticatedMeRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/answer-detail/$answerId': typeof AuthenticatedAnswerDetailAnswerIdRoute
  '/answer/$questionId': typeof AuthenticatedAnswerQuestionIdRoute
  '/me/blocked': typeof AuthenticatedMeBlockedRoute
  '/me/edit': typeof AuthenticatedMeEditRoute
  '/question/$questionId': typeof AuthenticatedQuestionQuestionIdRoute
  '/u/$handle': typeof AuthenticatedUHandleRouteWithChildren
  '/u/$handle/followers': typeof AuthenticatedUHandleFollowersRoute
  '/u/$handle/following': typeof AuthenticatedUHandleFollowingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/backlog': typeof AuthenticatedBacklogRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/grid': typeof AuthenticatedGridRoute
  '/home': typeof AuthenticatedHomeRoute
  '/me': typeof AuthenticatedMeRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/answer-detail/$answerId': typeof AuthenticatedAnswerDetailAnswerIdRoute
  '/answer/$questionId': typeof AuthenticatedAnswerQuestionIdRoute
  '/me/blocked': typeof AuthenticatedMeBlockedRoute
  '/me/edit': typeof AuthenticatedMeEditRoute
  '/question/$questionId': typeof AuthenticatedQuestionQuestionIdRoute
  '/u/$handle': typeof AuthenticatedUHandleRouteWithChildren
  '/u/$handle/followers': typeof AuthenticatedUHandleFollowersRoute
  '/u/$handle/following': typeof AuthenticatedUHandleFollowingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/backlog': typeof AuthenticatedBacklogRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/grid': typeof AuthenticatedGridRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/me': typeof AuthenticatedMeRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/answer-detail/$answerId': typeof AuthenticatedAnswerDetailAnswerIdRoute
  '/_authenticated/answer/$questionId': typeof AuthenticatedAnswerQuestionIdRoute
  '/_authenticated/me/blocked': typeof AuthenticatedMeBlockedRoute
  '/_authenticated/me/edit': typeof AuthenticatedMeEditRoute
  '/_authenticated/question/$questionId': typeof AuthenticatedQuestionQuestionIdRoute
  '/_authenticated/u/$handle': typeof AuthenticatedUHandleRouteWithChildren
  '/_authenticated/u/$handle/followers': typeof AuthenticatedUHandleFollowersRoute
  '/_authenticated/u/$handle/following': typeof AuthenticatedUHandleFollowingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/backlog'
    | '/feed'
    | '/grid'
    | '/home'
    | '/me'
    | '/notifications'
    | '/answer-detail/$answerId'
    | '/answer/$questionId'
    | '/me/blocked'
    | '/me/edit'
    | '/question/$questionId'
    | '/u/$handle'
    | '/u/$handle/followers'
    | '/u/$handle/following'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/backlog'
    | '/feed'
    | '/grid'
    | '/home'
    | '/me'
    | '/notifications'
    | '/answer-detail/$answerId'
    | '/answer/$questionId'
    | '/me/blocked'
    | '/me/edit'
    | '/question/$questionId'
    | '/u/$handle'
    | '/u/$handle/followers'
    | '/u/$handle/following'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/backlog'
    | '/_authenticated/feed'
    | '/_authenticated/grid'
    | '/_authenticated/home'
    | '/_authenticated/me'
    | '/_authenticated/notifications'
    | '/_authenticated/answer-detail/$answerId'
    | '/_authenticated/answer/$questionId'
    | '/_authenticated/me/blocked'
    | '/_authenticated/me/edit'
    | '/_authenticated/question/$questionId'
    | '/_authenticated/u/$handle'
    | '/_authenticated/u/$handle/followers'
    | '/_authenticated/u/$handle/following'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grid': {
      id: '/_authenticated/grid'
      path: '/grid'
      fullPath: '/grid'
      preLoaderRoute: typeof AuthenticatedGridRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/backlog': {
      id: '/_authenticated/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof AuthenticatedBacklogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/u/$handle': {
      id: '/_authenticated/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof AuthenticatedUHandleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/question/$questionId': {
      id: '/_authenticated/question/$questionId'
      path: '/question/$questionId'
      fullPath: '/question/$questionId'
      preLoaderRoute: typeof AuthenticatedQuestionQuestionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/edit': {
      id: '/_authenticated/me/edit'
      path: '/edit'
      fullPath: '/me/edit'
      preLoaderRoute: typeof AuthenticatedMeEditRouteImport
      parentRoute: typeof AuthenticatedMeRoute
    }
    '/_authenticated/me/blocked': {
      id: '/_authenticated/me/blocked'
      path: '/blocked'
      fullPath: '/me/blocked'
      preLoaderRoute: typeof AuthenticatedMeBlockedRouteImport
      parentRoute: typeof AuthenticatedMeRoute
    }
    '/_authenticated/answer/$questionId': {
      id: '/_authenticated/answer/$questionId'
      path: '/answer/$questionId'
      fullPath: '/answer/$questionId'
      preLoaderRoute: typeof AuthenticatedAnswerQuestionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/answer-detail/$answerId': {
      id: '/_authenticated/answer-detail/$answerId'
      path: '/answer-detail/$answerId'
      fullPath: '/answer-detail/$answerId'
      preLoaderRoute: typeof AuthenticatedAnswerDetailAnswerIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/u/$handle/following': {
      id: '/_authenticated/u/$handle/following'
      path: '/following'
      fullPath: '/u/$handle/following'
      preLoaderRoute: typeof AuthenticatedUHandleFollowingRouteImport
      parentRoute: typeof AuthenticatedUHandleRoute
    }
    '/_authenticated/u/$handle/followers': {
      id: '/_authenticated/u/$handle/followers'
      path: '/followers'
      fullPath: '/u/$handle/followers'
      preLoaderRoute: typeof AuthenticatedUHandleFollowersRouteImport
      parentRoute: typeof AuthenticatedUHandleRoute
    }
  }
}

interface AuthenticatedMeRouteChildren {
  AuthenticatedMeBlockedRoute: typeof AuthenticatedMeBlockedRoute
  AuthenticatedMeEditRoute: typeof AuthenticatedMeEditRoute
}

const AuthenticatedMeRouteChildren: AuthenticatedMeRouteChildren = {
  AuthenticatedMeBlockedRoute: AuthenticatedMeBlockedRoute,
  AuthenticatedMeEditRoute: AuthenticatedMeEditRoute,
}

const AuthenticatedMeRouteWithChildren = AuthenticatedMeRoute._addFileChildren(
  AuthenticatedMeRouteChildren,
)

interface AuthenticatedUHandleRouteChildren {
  AuthenticatedUHandleFollowersRoute: typeof AuthenticatedUHandleFollowersRoute
  AuthenticatedUHandleFollowingRoute: typeof AuthenticatedUHandleFollowingRoute
}

const AuthenticatedUHandleRouteChildren: AuthenticatedUHandleRouteChildren = {
  AuthenticatedUHandleFollowersRoute: AuthenticatedUHandleFollowersRoute,
  AuthenticatedUHandleFollowingRoute: AuthenticatedUHandleFollowingRoute,
}

const AuthenticatedUHandleRouteWithChildren =
  AuthenticatedUHandleRoute._addFileChildren(AuthenticatedUHandleRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedBacklogRoute: typeof AuthenticatedBacklogRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedGridRoute: typeof AuthenticatedGridRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedAnswerDetailAnswerIdRoute: typeof AuthenticatedAnswerDetailAnswerIdRoute
  AuthenticatedAnswerQuestionIdRoute: typeof AuthenticatedAnswerQuestionIdRoute
  AuthenticatedQuestionQuestionIdRoute: typeof AuthenticatedQuestionQuestionIdRoute
  AuthenticatedUHandleRoute: typeof AuthenticatedUHandleRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBacklogRoute: AuthenticatedBacklogRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedGridRoute: AuthenticatedGridRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMeRoute: AuthenticatedMeRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedAnswerDetailAnswerIdRoute:
    AuthenticatedAnswerDetailAnswerIdRoute,
  AuthenticatedAnswerQuestionIdRoute: AuthenticatedAnswerQuestionIdRoute,
  AuthenticatedQuestionQuestionIdRoute: AuthenticatedQuestionQuestionIdRoute,
  AuthenticatedUHandleRoute: AuthenticatedUHandleRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
