-- Reports table
CREATE TABLE public.reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_id UUID NOT NULL,
  target_type TEXT NOT NULL CHECK (target_type IN ('answer','comment','user')),
  target_answer_id BIGINT,
  target_comment_id BIGINT,
  target_user_id UUID,
  reason TEXT NOT NULL,
  detail TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT, DELETE ON public.reports TO authenticated;
GRANT ALL ON public.reports TO service_role;

ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users view own reports" ON public.reports
FOR SELECT TO authenticated USING (auth.uid() = reporter_id);

CREATE POLICY "users insert own reports" ON public.reports
FOR INSERT TO authenticated WITH CHECK (auth.uid() = reporter_id);

CREATE INDEX idx_reports_reporter ON public.reports(reporter_id);

-- Blocks table
CREATE TABLE public.blocks (
  blocker_id UUID NOT NULL,
  blocked_id UUID NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (blocker_id, blocked_id),
  CHECK (blocker_id <> blocked_id)
);

GRANT SELECT, INSERT, DELETE ON public.blocks TO authenticated;
GRANT ALL ON public.blocks TO service_role;

ALTER TABLE public.blocks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users view own blocks" ON public.blocks
FOR SELECT TO authenticated USING (auth.uid() = blocker_id);

CREATE POLICY "users insert own blocks" ON public.blocks
FOR INSERT TO authenticated WITH CHECK (auth.uid() = blocker_id);

CREATE POLICY "users delete own blocks" ON public.blocks
FOR DELETE TO authenticated USING (auth.uid() = blocker_id);

CREATE INDEX idx_blocks_blocker ON public.blocks(blocker_id);
CREATE INDEX idx_blocks_blocked ON public.blocks(blocked_id);