
-- 1) answers: 캡션 제거 + 여러 장 사진 지원
ALTER TABLE public.answers ADD COLUMN IF NOT EXISTS photos text[] NOT NULL DEFAULT '{}';

-- 기존 photo_url 데이터를 photos 배열로 이관
UPDATE public.answers SET photos = ARRAY[photo_url] WHERE photo_url IS NOT NULL AND array_length(photos, 1) IS NULL;

ALTER TABLE public.answers DROP COLUMN IF EXISTS caption;
ALTER TABLE public.answers DROP COLUMN IF EXISTS photo_url;

-- 빈 배열 답변 방지
ALTER TABLE public.answers ADD CONSTRAINT answers_photos_nonempty CHECK (array_length(photos, 1) >= 1);

-- 2) comments 테이블
CREATE TABLE public.comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  answer_id BIGINT NOT NULL REFERENCES public.answers(id) ON DELETE CASCADE,
  user_id UUID NOT NULL,
  body TEXT NOT NULL CHECK (char_length(body) BETWEEN 1 AND 300),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_comments_answer ON public.comments(answer_id, created_at DESC);

GRANT SELECT ON public.comments TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.comments TO authenticated;
GRANT ALL ON public.comments TO service_role;

ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "comments on public answers viewable by everyone"
ON public.comments FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM public.answers a
    WHERE a.id = comments.answer_id AND a.visibility = 'public'
  )
);

CREATE POLICY "authenticated users insert own comments"
ON public.comments FOR INSERT TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "users update own comments"
ON public.comments FOR UPDATE TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "users delete own comments"
ON public.comments FOR DELETE TO authenticated
USING (auth.uid() = user_id);
