
-- Helper: 상호 팔로우 = 친구 판정
CREATE OR REPLACE FUNCTION public.are_mutual_follows(_a uuid, _b uuid)
RETURNS boolean
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.follows
    WHERE follower_id = _a AND following_id = _b
  ) AND EXISTS (
    SELECT 1 FROM public.follows
    WHERE follower_id = _b AND following_id = _a
  );
$$;

-- Nudges 테이블
CREATE TABLE public.nudges (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id uuid NOT NULL,
  receiver_id uuid NOT NULL,
  question_id bigint NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL DEFAULT now(),
  responded_at timestamptz,
  CONSTRAINT nudges_status_chk CHECK (status IN ('pending', 'answered', 'dismissed')),
  CONSTRAINT nudges_no_self CHECK (sender_id <> receiver_id),
  CONSTRAINT nudges_unique UNIQUE (sender_id, receiver_id, question_id)
);

CREATE INDEX nudges_receiver_idx ON public.nudges (receiver_id, created_at DESC);
CREATE INDEX nudges_sender_idx ON public.nudges (sender_id, created_at DESC);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.nudges TO authenticated;
GRANT ALL ON public.nudges TO service_role;

ALTER TABLE public.nudges ENABLE ROW LEVEL SECURITY;

-- 받은/보낸 본인만 조회
CREATE POLICY "users view own nudges"
  ON public.nudges FOR SELECT TO authenticated
  USING (auth.uid() = sender_id OR auth.uid() = receiver_id);

-- 상호 팔로우 관계여야만 보낼 수 있음 + 차단 관계 아닐 때
CREATE POLICY "mutual friends insert nudges"
  ON public.nudges FOR INSERT TO authenticated
  WITH CHECK (
    auth.uid() = sender_id
    AND public.are_mutual_follows(sender_id, receiver_id)
    AND NOT public.is_blocked_by(receiver_id)
  );

-- 받는 사람: status 변경 가능 (answered/dismissed)
CREATE POLICY "receiver updates own nudges"
  ON public.nudges FOR UPDATE TO authenticated
  USING (auth.uid() = receiver_id)
  WITH CHECK (auth.uid() = receiver_id);

-- 보낸 사람: 자기가 보낸 거 취소 가능
CREATE POLICY "sender deletes own nudges"
  ON public.nudges FOR DELETE TO authenticated
  USING (auth.uid() = sender_id);

-- Rate limit: sender당 1일 20개
CREATE OR REPLACE FUNCTION public.enforce_nudges_rate_limit()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE c int;
BEGIN
  SELECT count(*) INTO c FROM public.nudges
    WHERE sender_id = NEW.sender_id AND created_at > now() - interval '1 day';
  IF c >= 20 THEN
    RAISE EXCEPTION '오늘은 더 이상 넛지를 보낼 수 없어요. 내일 다시 시도해 주세요.';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER nudges_rate_limit
  BEFORE INSERT ON public.nudges
  FOR EACH ROW EXECUTE FUNCTION public.enforce_nudges_rate_limit();

-- 답변 시 자동으로 pending → answered
CREATE OR REPLACE FUNCTION public.mark_nudges_answered()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.nudges
    SET status = 'answered', responded_at = now()
    WHERE receiver_id = NEW.user_id
      AND question_id = NEW.question_id
      AND status = 'pending';
  RETURN NEW;
END;
$$;

CREATE TRIGGER answers_mark_nudges
  AFTER INSERT ON public.answers
  FOR EACH ROW EXECUTE FUNCTION public.mark_nudges_answered();
